name: Build and Sign APKs

on:
  push:
    branches:
      - 'master'

jobs:
  build-release:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:focal
      volumes:
        - android-app-keystore:/keystore

    steps:
      - name: Fix Permissions
        run: |
          apt update && apt upgrade -y
          apt install -y unzip openjdk-17-jdk

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Generate Keystore File
        run: |
          echo "Generating keystore..."
          keytool -genkeypair \
            -keystore $GITHUB_WORKSPACE/keystore.jks \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass ${{ secrets.STORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            -alias ${{ secrets.KEY_ALIAS }} \
            -dname "CN=OpenEUICC\,OU=Development\,O=Example\,L=City\,S=State\,C=US"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Release APK
        run: |
          echo "Building release APK..."
          ./gradlew clean :app:assembleRelease --stacktrace

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Release APKs
          path: app/build/outputs/apk/release/*.apk
