name: Build APKs without Keystore

on:
  push:
    branches:
      - 'master'

jobs:
  build-debug:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:focal

    steps:
      - name: Fix Permissions
        run: |
          apt update && apt upgrade -y
          apt install -y unzip openjdk-17-jdk

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2
          ndk-version: 25.1.8937393

      - name: Build Debug APK
        run: |
          echo "Building debug APK..."
          ./gradlew clean :app:assembleDebug --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: Debug APK
          path: app/build/outputs/apk/debug/*.apk
