name: Build APKs

on:
  push:
    branches:
      - 'master'

jobs:
  build-debug:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:focal

    steps:
      - name: Install Dependencies
        run: |
          apt update && apt upgrade -y
          apt install -y unzip openjdk-17-jdk curl

      - name: Set up Android SDK
        run: |
          echo "Setting up Android SDK..."
          mkdir -p $HOME/android-sdk
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q sdk-tools.zip -d $HOME/android-sdk
          rm sdk-tools.zip
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Set ANDROID_HOME
        run: |
          echo "Setting ANDROID_HOME environment variable..."
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/bin:$PATH" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build Debug APK
        run: |
          echo "Building debug APK..."
          ./gradlew clean :app:assembleDebug --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: Debug APK
          path: app/build/outputs/apk/debug/*.apk
